import type { MockCreative, MockTheme } from "../types";

export const MOCK_CREATIVES: Record<MockTheme, MockCreative[]> = {
  tech: [
    {
      id: "tech-cloud",
      theme: "tech",
      brand: "HyperScale Cloud",
      tagline: "Deploy Next.js 15 apps globally with 0ms cold starts & instant edge DB.",
      ctaText: "Claim $200 Free Credits",
      ctaUrl: "https://example.com/hyperscale",
      accentColor: "#3b82f6",
      bgGradient: "linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%)",
      category: "Developer Tools",
      badge: "Sponsored • Developer Cloud",
      imageIcon: "⚡",
    },
    {
      id: "tech-db",
      theme: "tech",
      brand: "NeonFlux Database",
      tagline: "Serverless Postgres with branching, time-travel queries, and autoscaling.",
      ctaText: "Start Free Tier",
      ctaUrl: "https://example.com/neonflux",
      accentColor: "#10b981",
      bgGradient: "linear-gradient(135deg, #064e3b 0%, #022c22 100%)",
      category: "Databases",
      badge: "Ad • Infrastructure",
      imageIcon: "🐘",
    },
  ],
  saas: [
    {
      id: "saas-analytics",
      theme: "saas",
      brand: "PulseMetrics AI",
      tagline: "Real-time user analytics without cookies or GDPR consent banners.",
      ctaText: "Try 14-Day Free Trial",
      ctaUrl: "https://example.com/pulsemetrics",
      accentColor: "#8b5cf6",
      bgGradient: "linear-gradient(135deg, #2e1065 0%, #4c1d95 100%)",
      category: "Analytics & Growth",
      badge: "Promoted • Analytics",
      imageIcon: "📊",
    },
    {
      id: "saas-crm",
      theme: "saas",
      brand: "FlowDesk CRM",
      tagline: "The all-in-one workspace for closing B2B deals 3x faster with AI copilot.",
      ctaText: "Book a Demo",
      ctaUrl: "https://example.com/flowdesk",
      accentColor: "#ec4899",
      bgGradient: "linear-gradient(135deg, #500724 0%, #831843 100%)",
      category: "Productivity",
      badge: "Sponsored • Sales Tool",
      imageIcon: "💼",
    },
  ],
  food: [
    {
      id: "food-chef",
      theme: "food",
      brand: "Artisan Kitchen Co.",
      tagline: "Japanese Damascus steel chef knife crafted for effortless razor-sharp slicing.",
      ctaText: "Save 30% Today",
      ctaUrl: "https://example.com/artisankitchen",
      accentColor: "#f59e0b",
      bgGradient: "linear-gradient(135deg, #451a03 0%, #78350f 100%)",
      category: "Cookware & Kitchen",
      badge: "Sponsored • Kitchen Gear",
      imageIcon: "🔪",
    },
    {
      id: "food-box",
      theme: "food",
      brand: "OrganicFarm Basket",
      tagline: "Farm-to-table organic vegetables and grass-fed meats delivered weekly.",
      ctaText: "Get Free First Box",
      ctaUrl: "https://example.com/organicfarm",
      accentColor: "#22c55e",
      bgGradient: "linear-gradient(135deg, #14532d 0%, #166534 100%)",
      category: "Meal Kits",
      badge: "Ad • Fresh Food",
      imageIcon: "🥗",
    },
  ],
  ecommerce: [
    {
      id: "ecom-shoes",
      theme: "ecommerce",
      brand: "AeroGlide Runner",
      tagline: "Ultra-lightweight carbon fiber running shoes engineered for peak marathon speed.",
      ctaText: "Shop the Collection",
      ctaUrl: "https://example.com/aeroglide",
      accentColor: "#06b6d4",
      bgGradient: "linear-gradient(135deg, #164e63 0%, #0e7490 100%)",
      category: "Sportswear",
      badge: "Sponsored • Footwear",
      imageIcon: "👟",
    },
  ],
  travel: [
    {
      id: "travel-escape",
      theme: "travel",
      brand: "Nordic Haven Escapes",
      tagline: "Private glass igloos in Lapland with front-row Northern Lights views.",
      ctaText: "Explore Winter Deals",
      ctaUrl: "https://example.com/nordic",
      accentColor: "#38bdf8",
      bgGradient: "linear-gradient(135deg, #0c4a6e 0%, #075985 100%)",
      category: "Vacations",
      badge: "Promoted • Luxury Travel",
      imageIcon: "❄️",
    },
  ],
  finance: [
    {
      id: "fin-invest",
      theme: "finance",
      brand: "ApexWealth Portfolio",
      tagline: "Automated index investing with zero management fees and tax-loss harvesting.",
      ctaText: "Open Account with $0",
      ctaUrl: "https://example.com/apexwealth",
      accentColor: "#eab308",
      bgGradient: "linear-gradient(135deg, #422006 0%, #713f12 100%)",
      category: "Fintech & Investing",
      badge: "Sponsored • Investing",
      imageIcon: "📈",
    },
  ],
};

export function getMockCreative(theme: MockTheme = "tech", index = 0): MockCreative {
  const creatives = MOCK_CREATIVES[theme] || MOCK_CREATIVES.tech;
  return creatives[index % creatives.length];
}
